### PR TITLE
fix(docs): correct rendering of the plugin README on plugins.jenkins.io

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR replaces the relative `examples` link by an absolute one, to avoid a 404 error when clicking on this link from the plugin description page on plugins.jenkins.io.

On https://plugins.jenkins.io/kubernetes-credentials-provider/ `examples` currently links to https://plugins.jenkins.io/kubernetes-credentials-provider/examples (not found)

Closes https://github.com/jenkins-infra/plugin-site/issues/1519

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by jtnord — COMMENTED** [review]
there is no gaurnatee that this is where the file ends up - it may depend on how the site is built.

Additionally there are other relative links in this page.

But more importantly the plugin page is showing garbage anyway - it just can not handle the macros etc here.

so I would say this is a problem with the site generation used upstream - it should use what the plugin uses and if needed set a base URL.

e.g. see this nonsense in the plugins.jenkins.io page
image

**Comment by lemeurherve** [comment]
> there is no gaurnatee that this is where the file ends up - it may depend on how the site is built.

Having absolute links like this one should ensure the user consulting them would be redirected to the right place.

> Additionally there are other relative links in this page.

You're right, they should be dealt with too.

> But more importantly the plugin page is showing garbage anyway - it just can not handle the macros etc here.
> 
> so I would say this is a problem with the site generation used upstream - it should use what the plugin uses and if needed set a base URL.
> 
> e.g. see this nonsense in the plugins.jenkins.io page image

Not sure if it worth the hassle of implementing additional code in the plugin site just for this plugin and maybe a handful more* using a custom doc generation.

I though the override to use the docs/README.md page as plugin description on plugins.jenkins.io would have been specified in  but it's not the case, I need to dig plugin-site source code to find out how it's done in that case.

<sup>*</sup>: I don't know if there a way to identify plugins using custom GitHub pages for their doc, it's the first one I'm noticing.

**Comment by lemeurherve** [comment]
Oh... From https://github.com/jenkins-infra/helpdesk/issues/3770#issuecomment-1744328453 the plugin site is using https://updates.jenkins.io/current/plugin-documentation-urls.json as source to know which page to fetch for plugins.jenkins.io plugin description.

From the updates.jenkins.io JSON, the URL used is https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/blob/master/docs/README.md

I'd like to try an override using the GitHub page link instead, WDYT @jtnord?

**Comment by jtnord** [comment]
> > there is no gaurnatee that this is where the file ends up - it may depend on how the site is built.
> 
> Having absolute links like this one should ensure the user consulting them would be redirected to the right place.

but not from the pages that are used to build them.

There is something fishy going on - how is say the [google-kubernetes](https://plugins.jenkins.io/google-kubernetes-engine/) working - its readme is using a relative link in the root.   (note jenkins.io is not linking to my repos readme but into the GH-docs pages README.

> > Additionally there are other relative links in this page.
> 
> You're right, they should be dealt with too.
> 
> > But more importantly the plugin page is showing garbage anyway - it just can not handle the macros etc here.
> > so I would say this is a problem with the site generation used upstream - it should use what the plugin uses and if needed set a base URL.
> > e.g. see this nonsense in the plugins.jenkins.io page image
> 
> Not sure if it worth the hassle of implementing additional code in the plugin site just for this plugin and maybe a handful more* using a custom doc generation.
> 
> I though the override to use the docs/README.md page as plugin description on plugins.jenkins.io would have been specified in https://github.com/jenkins-infra/update-center2/blob/master/resources/wiki-overrides.properties but it's not the case, I need to dig plugin-site source code to find out how it's done in that case.

> *: I don't know if there a way to identify plugins using custom GitHub pages for their doc, it's the first one I'm noticing.

having a separate page for the repo and plugins.jenkins.io is fine by me - there already exists one which redirects to the GH pages.

**Comment by lemeurherve** [comment]
> There is something fishy going on - how is say the [google-kubernetes](https://plugins.jenkins.io/google-kubernetes-engine/) working - its readme is using a relative link in the root. (note jenkins.io is not linking to my repos readme but into the GH-docs pages README.

I've added `./` at the beginning of the two relative paths in the README, not sure if it's the correct fix but it can't hurt.

Tested on my fork: https://lemeurherve.github.io/kubernetes-credentials-provider-plugin/

> I need to dig plugin-site source code to find out how it's done in that case.

There is no override, the update-center2 job is retrieving the URL from the pom.xml, hence https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/79/commits/18e27cfe93f6095f21457deb2e886419b471da5d

@jtnord do you think we could try this change? I'll deal with the revert if it's not working, and if it works it won't need another distinct README.

**Review by jtnord — APPROVED** [review]

**Comment by jtnord** [comment]
> > There is something fishy going on - how is say the [google-kubernetes](https://plugins.jenkins.io/google-kubernetes-engine/) working - its readme is using a relative link in the root. (note jenkins.io is not linking to my repos readme but into the GH-docs pages README.
> 
> I've added `./` at the beginning of the two relative paths in the README, not sure if it's the correct fix but it can't hurt.
> 
> Tested on my fork: https://lemeurherve.github.io/kubernetes-credentials-provider-plugin/
> 
> > I need to dig plugin-site source code to find out how it's done in that case.
> 
> There is no override, the update-center2 job generating https://updates.jenkins.io/current/plugin-documentation-urls.json is retrieving the URL from the pom.xml, hence [18e27cf](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/commit/18e27cfe93f6095f21457deb2e886419b471da5d) where I've put the GitHub page URL instead of the docs/README.md one.
> 
> @jtnord do you think we could try this change? I'll deal with the revert if it's not working, and if it works it won't need another distinct README.

does this need a release or does pliugins.jenkins.io pick up the live page?

**Comment by lemeurherve** [comment]
No need for a new release, the update-center2 job is running every 3 minutes on trusted.ci.jenkins.io, then it's the plugin site job that will retrieve and use the generated JSON.

I'll keep you informed in this PR.

**Comment by lemeurherve** [comment]
> AFAIU no need for a new release

I was wrong. Could you cut a new release please @jtnord ?

**Comment by jtnord** [comment]
> > AFAIU no need for a new release
> 
> I was wrong. Could you cut a new release please @jtnord ?

release in progress will show up in https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/releases when done.

**Comment by lemeurherve** [comment]
In the end this is worst 😓 The header table is now rendered, the relative links are still not working, and the macros are still raw displayed: https://plugins.origin.jenkins.io/kubernetes-credentials-provider/

Preparing another PR with a distinct README.

**Comment by zbynek** [comment]
btw. instead of Jekyll's highlight macro you can use the markdown syntax ```groovy ... ```, works well when rendered on GitHub and should work with Jekyll as well: https://jun711.github.io/web/how-to-highlight-code-on-a-Jekyll-site-syntax-highlighting/#example-with-language-specified

**Pull request merged**
