### PR TITLE
Compatibility with kubernetes-client 6.x

### PR DESCRIPTION
**Pull request by Vlatombe**
Main compatibility has been fixed through https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/73, this is making the plugin depend on kubernetes-client 6.x at compile time and allows additional cleanup.

* Jenkins 2.332.4
* Use Jenkins BOM
* Kubernetes-client-api 6.x

Downstream of https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/163

I initially thought this plugin was compatible with the new kubernetes-client version. I missed the fact their `KubernetesClient` builder is now unusable out of the box in Jenkins context as it assumes context class loader = calling class classloader, which is not the case in the context of Jenkins classloading.

The main fix is very simple but unfortunately needs to be applied.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jtnord** [comment]
> Any idea when this might get reviewed and released?

not until the end of the month.

**Comment by Vlatombe** [comment]
@jtnord Yes, it's probably harmless. I can do that.

**Comment by Vlatombe** [comment]
@jtnord https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/73

**Comment by jtnord** [comment]
@pashcan you should be able to use the [release from yesterday](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/releases/tag/1.208.v128ee9800c04).   This PR remains for me to cleanup some tech debt

**Review by jtnord — APPROVED** [review]

**Pull request merged**
