### PR TITLE
Adding support for Azure Service Principal and Managed Identity Jenkins credentials

### PR DESCRIPTION
**Pull request by TooDissing**
### Azure Credentials
With this PR I am adding support for creating Azure Service Principal and Azure Managed Identity credentials using a Kubernetes secret.
Two different secret converters are created as each credential type requires different fields.
The Azure environment defaults to "Azure" which is the main cloud, but can also be specified explicitly in both credential types.

There's also added some example files and I have updated the documentation with those.

### Testing done
I have create several unit tests for each credential type as well as some manual tests against a live environment.
This by creating a k8s secret for the service principal which this plugin then converts into a Azure Service Principal credential.

I have added several unit tests that tests both valid and invalid secret manifest files.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
Not the plugin maintainer here. But probably preferable to create extension plugin like ?

https://plugins.jenkins.io/openshift-k8s-credentials/
https://plugins.jenkins.io/phabricator-k8s/
https://plugins.jenkins.io/gitlab-kubernetes-credentials/
https://plugins.jenkins.io/bitbucket-kubernetes-credentials/

In my opinion the `kubernetes-credentials-provider-plugin`should only support basic credentials like SSH, string, username/password. All other services must be extensions.

**Comment by TueDissingWork** [comment]
> Not the plugin maintainer here. But probably preferable to create extension plugin like ?
> 
> https://plugins.jenkins.io/openshift-k8s-credentials/ https://plugins.jenkins.io/phabricator-k8s/ https://plugins.jenkins.io/gitlab-kubernetes-credentials/ https://plugins.jenkins.io/bitbucket-kubernetes-credentials/
> 
> In my opinion the `kubernetes-credentials-provider-plugin`should only support basic credentials like SSH, string, username/password. All other services must be extensions.

That makes sense - didn't konw it was an option.

Tried to create an extension based on the gitlab one, but are having some problems getting it to recognize my secrets. Any guides on how to approach this somewhere?

**Comment by jonesbusy** [comment]
Please link your repository and error you are getting.

I maintain the gitlab, openshift and bitbucket one and didn't faced such issue.

**Comment by TueDissingWork** [comment]
> Please link your repository and error you are getting.
> 
> I maintain the gitlab, openshift and bitbucket one and didn't faced such issue.

Sure thing.

The repo is here: https://github.com/TueDissingWork/azure-kubernetes-credentials-plugin
And I am getting this error in the Jenkins log, when trying to add a secret of the `azureServicePrincipal` type:
```
2024-01-04 09:05:58.329+0000 [id=264]    WARNING    c.c.j.p.k.KubernetesCredentialProvider#convertSecret: No SecretToCredentialConvert
```

When debugging the Jenkins instanse I see that the following code returns `null` ([KubernetesCredentialProvider.java:302](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/blob/95949f923aae4c2261bb5d187aeafb5e60683510/src/main/java/com/cloudbees/jenkins/plugins/kubernetes_credentials_provider/KubernetesCredentialProvider.java#L302C9-L302C87)):
```
SecretToCredentialConverter lookup = SecretToCredentialConverter.lookup(type);
````

So I suspect that my `@Extension` isn't getting correctly. No class of the expected type seems to be found by Jenkins.

**Comment by jonesbusy** [comment]
Can be closed in favor of https://github.com/jenkinsci/azure-kubernetes-credentials-plugin

**Comment by Fenil-Patelll** [comment]
@jonesbusy @TooDissing @TueDissingWork. Sorry to disturb you guys. This is out of topic but I am not able to find the answer on google, though to talk here

I am adding GCP service account credentials as a secret to Jenkins(deployed on Kubernetes) using the Kubernetes Credential Provider plugin.

The secrets are successfully created and added to my Jenkins namespace(on kubernetes cluster), but when I go to the Jenkins Credentials Page, I can not see my gcp credentials

Are you guys supporting the gcp service account JSON file credentials to be stored as a secret through the Kubernetes Credential Provide plugin?

**Comment by jonesbusy** [comment]
Looking at https://plugins.jenkins.io/kubernetes-credentials-provider/dependencies/ I don't see anything particular related to google cloud.

Probably a extension plugin is needed

**Comment by Fenil-Patelll** [comment]
thanks for clarifying, I found a way to do it [Secret File](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/#:~:text=text%3A%20MySecret-,Secret,-File). 

We can encode the GCP Service account JSON Credential files and put it as a SecretFile as a Kubernetes secrets. It works

**Pull request closed without merging**
