### PR TITLE
Introduce kubeconfig credentials used by kubernetes-cd-plugin

### PR DESCRIPTION
**Pull request by topikachu**
Add support for kubernetes-cd-plugin's credentials

### CODE REVIEW

**Comment by topikachu** [comment]
Hi, @jtnord 
Would you please review my change. We use the kubernetes-cd-plugin and want a unique solution to manage all credentials.

**Comment by jtnord** [comment]
kubeconfig should not be a credential, it is configuration not security.
as such I have no idea why it should be managed as such.  rather it should be using the config file provider plugin with a specific type (June config) along with credentials for the certificates.

**Comment by topikachu** [comment]
@jtnord kubeconfig can have an inline credential (token or certificate in base64 format). However, the point is [kubeconfig credentials](https://github.com/jenkinsci/kubernetes-cd-plugin/blob/dev/src/main/java/com/microsoft/jenkins/kubernetes/credentials/KubeconfigCredentials.java)  is used by [kubernetes-cd-plugin](https://github.com/jenkinsci/kubernetes-cd-plugin). And I'd like to keep current pipeline working, which uses kubernetes-cd-plugin, without a big change.

**Comment by jtnord** [comment]
so can maven config, it can be managed by config file provider and credentials.

**Comment by jtnord** [comment]
you can add support in different plugins.
the extension does not have to be implemented here, it can be done in the kube CD  plugin or a new plugin, but as I strongly believe this is abusing credentials I do not want to endorse that behaviour.

**Pull request closed without merging**
